language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'forcerequire' ]; then cd .. && eval "mv $currentfolder forcerequire" && cd forcerequire; fi
